// <auto-generated />
namespace Mighty_Maestro.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class KeyinAsnwer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(KeyinAsnwer));
        
        string IMigrationMetadata.Id
        {
            get { return "202108010210550_Key in Asnwer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
